services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my-network-1
    env_file:
      - ./server/.env
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - my-network-1
    depends_on:
      - server
networks:
  my-network-1:
    driver: bridge
